### ISSUE TITLE
Tuya local_key using frida not obtainable (app name different?)

### ISSUE THREAD

**Issue by BrendanxP** [AboveColin/HA-Philips-Pet-Series#4]
I have been trying to get the local_key using frida but without any luck. 

I just freshly rooted my (spare) phone, on Android 14 using Magisk. I then tried to install frida over adb which gave some issues, after which I installed the [MagiskFrida module](https://github.com/ViRb3/magisk-frida?tab=readme-ov-file).
This seems to work well as I am able to trace chrome activity using `frida-trace -U -i open -N com.android.chrome`, where I have my android device connected over adb USB and run the command from Windows 11 cmd.

The command posted in the repo does however not work. 
`Failed to spawn: unable to find application with identifier 'com.versuni.petsseries'`

When I do `frida-ps -U`, I do get the following items among many others:
`11419  Philips Pets Series
11503  com.versuni.nbx.petsseries:monitor`

However, changing the code to any of the following,
`frida-trace -U --decorate -j '*!*encodeString*' -f com.versuni.nbx.petsseries
frida-trace -U --decorate -j '*!*encodeString*' -p 11419
frida-trace -U --decorate -j '*!*encodeString*' -p 11503`
will yield
`Started tracing 0 functions. Web UI available at http://localhost:53685/`
where the web ui crashes and nothing appears when I add an output file.

I also assume the output file should look like the following, but this was not really clear from the documention:
`-o "C:/Users/xxx/Documents/output.txt"`

I would very much appreciate some help with this, thanks!

__
edit:
I am on app version 1.1.0, released on June 7, 2024.

**Comment by AboveColin** [comment]
Hi, good to know! If you add :monitor to com.versuni.nbx.petsseries in the command like com.versuni.nbx.petsseries:monitor ? Will it then work correctly?

**Comment by BrendanxP** [comment]
> Hi, good to know! If you add :monitor to com.versuni.nbx.petsseries in the command like com.versuni.nbx.petsseries:monitor ? Will it then work correctly?

Hi @AboveColin, thanks for your quick response! Unfortunately that also did not work (and still does not as I gave it a second try).
`frida-trace -U --decorate -j '*!*encodeString*' -f "com.versuni.nbx.petsseries:monitor"
Failed to spawn: unable to find application with identifier 'com.versuni.nbx.petsseries:monitor'`

`frida-trace -U --decorate -j '*!*encodeString*' -f com.versuni.nbx.petsseries:monitor
Failed to spawn: unable to find application with identifier 'com.versuni.nbx.petsseries:monitor'`

Thats why I also tried it with the PIDs instead of the names, but with no luck as mentioned in the first post :(

**Comment by AboveColin** [comment]
@BrendanxP i'll try the steps for myself tomorrow (if i got the time, otherwise Monday) and will report back if I found anything that's different, sorry for the inconvenience!

**Comment by AboveColin** [comment]
@BrendanxP heyhey! Tried it again and indeed it doesn't register anymore, will try more the coming days and i'll let you know!

**Comment by AboveColin** [comment]
@BrendanxP Got it working again with this command, while connected over USB

frida-trace -U --decorate \
  -j '*!*encodeString*' \
  -f com.versuni.nbx.petsseries \
  -o output.txt
  
  Can you verify that works, then i'll add that to the readme, thanks for letting me know!

**Comment by BrendanxP** [comment]
> @BrendanxP Got it working again with this command, while connected over USB
> 
> ```shell
> frida-trace -U --decorate \
>   -j '*!*encodeString*' \
>   -f com.versuni.nbx.petsseries \
>   -o output.txt
> ```
> 
> Can you verify that works, then i'll add that to the readme, thanks for letting me know!

@AboveColin Thanks for your quick response to this matter. I'll test it later today when I am back home with access to the rooted phone and let you know asap ;)

**Comment by BrendanxP** [comment]
> @BrendanxP Got it working again with this command, while connected over USB
> 
> ```shell
> frida-trace -U --decorate \
>   -j '*!*encodeString*' \
>   -f com.versuni.nbx.petsseries \
>   -o output.txt
> ```
> 
> Can you verify that works, then i'll add that to the readme, thanks for letting me know!

It does connect to the app but then finds 0 functions. So it simply does not output anything. Do you know what script the function "encodeString" should be part of?

**Comment by BrendanxP** [comment]
Oh wow. It were the apostrophes that happened to be the issue. The following code works:
`frida-trace -U --decorate -j *!*encodeString* -N com.versuni.nbx.petsseries -o output.txt`

My only concern is that the formatting of the local key is a little confusing, with the following key, should I consider everything between the apostrophes, or exclude the backslash as well?
`"localKey\":\"FceXXX]+$7}9Zl.\"`
So should one enter:
`"FceXXX]+$7}9Zl.\"`, 
`FceXXX]+$7}9Zl.\`
or
`FceXXX]+$7}9Zl.`

I believe this could be clarified in the readme and then it is perfect.
