### ISSUE TITLE
Feature Request: Allow users to reenter the tokens

### ISSUE THREAD

**Issue by NickVulkers** [AboveColin/HA-Philips-Pet-Series#6]
Right now the only way to check if the authentication problems described in https://github.com/AboveColin/HA-Philips-Pet-Series/issues/2 are working is to completely remove the current device, and add a new entry. It would improve usability if we could reenter the tokens for authentication.

**Comment by AboveColin** [comment]
Working on it atm! Got a first fix working already!

**Comment by AboveColin** [comment]
Added the feature in PR #7 ! Could you try it out before I merge it?

**Comment by NickVulkers** [comment]
> Added the feature in PR #7 !

Awesome, I just tested it and it successfully reauthenticates!
